### PR TITLE
Mostro Interface

### PR DESCRIPTION
**Pull request by AndreaDiazCorreia**
This pull request introduces the core Mostro implementation through mostro.ts, which serves as the main interface for interacting with the Mostro protocol.

For now it's only the initial interface

Related Issue #12 

## Summary by CodeRabbit

- **New Features**
	- Introduced a new `Mostro` class for Nostr-based protocol communication with various event handling capabilities.
	- Added a new dependency: `@nostr-dev-kit/ndk`.

- **Documentation**
	- Updated `CONTRIBUTING.md` for clearer contributor guidance and detailed development workflow instructions.
	- Reformatted `README.md` for improved clarity and organization.

- **Bug Fixes**
	- Enhanced error handling in test cases for the `createOrder` function.

- **Style**
	- Various formatting improvements across multiple files, including consistent use of semicolons and streamlined function signatures.

- **Chores**
	- Minor updates to configuration files, including adding newlines for better formatting.

### CODE REVIEW

**Comment by AndreaDiazCorreia** [comment]
@coderabbitai review

**Comment by grunch** [comment]
@AndreaDiazCorreia can you add tests, so developer can see how to use the library?

**Comment by AndreaDiazCorreia** [comment]
I am working on that with listing orders, create orders and take orders

**Comment by AndreaDiazCorreia** [comment]
This was only the interface similar to the interface in the actual web client

**Pull request merged**
